# BACKEND DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      # This tells AKS to use your Docker Hub "key"
      imagePullSecrets:
        - name: dockerhub-auth
      containers:
      - name: backend-container
        # UPDATED: Points to your Docker Hub repo
        image: shivaamaroju/email-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: gemini-secrets
              key: GEMINI_API_KEY
        - name: GEMINI_API_URL
          valueFrom:
            secretKeyRef:
              name: gemini-secrets
              key: GEMINI_API_URL
---
# FRONTEND DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: dockerhub-auth
      containers:
      - name: frontend-container
        # UPDATED: Points to your Docker Hub repo
        image: shivaamaroju/email-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
