spring.application.name=EmailWriter
server.port=8081
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?=
gemini.api.key=AIzaSyC72-jWJx8j8jScyHJd6QmaCjvLcphnRBU